apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-kews
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-bundle-tenant/appstudio/dc-metro-map-kews@sha256:d1f8deffe5145bd6571d8665f051f9ff79df4311e02ba170441c61eba8dab0bb
        name: my-nodejs
        resources: {}
status: {}
